### ISSUE TITLE
SoilMoistureProfiles generates an error when running on CONUS that is hard to trace 

### ISSUE THREAD

**Issue by stcui007** [NOAA-OWP/SoilMoistureProfiles#13]
Current Behavior:
In a recent run at CONUS scale, I encountered the following error:
`ngen: /home/shengting.cui/ngen_baseline/ngen/extern/SoilMoistureProfiles/SoilMoistureProfiles/src/soil_moisture_profile.cxx:553: void soil_moisture_profile::SoilMoistureProfileFromConceptualReservoir(soil_moisture_profile::soil_profile_parameters*): Assertion `parameters->soil_moisture_profile[i] > 0.0' failed.`

This error seems to be related to the following codes in the` soil_moisture_profile.cxx, line 451, 461, 532, `where `parameters->soil_moisture_profile[i] `is set. It is uncertain at the moment whether the error is caused by `0 value of smcmax or satpsi or both `at the moment. 

Expected behavior:
Keep the code running until it print out all the cat-id's in the form:
`time step = XXXX, smcmax[0] = xxxx, satpsi = xxxx, cat_id = xxxx.`

**Comment by ajkhattak** [comment]
@stcui007 could be please pull and rerun? We had checks on zero `smcmax` but not on `satpsi` that I just added. Hope it will resolve the issue.

**Comment by stcui007** [comment]
I think I have resolved the problem.
